#!/bin/bash
echo This file creates directory layout based on Ansible documentation resides on http://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html
touch production
touch staging
mkdir group_vars
mkdir host_vars
mkdir library
mkdir module_utils
mkdir filter_plugins
touch site.yml
touch webservers.yml
touch dbservers.yml
touch services.yml
mkdir roles
cd roles
mkdir common
mkdir webtier
mkdir monitoring
cd common
mkdir tasks
touch tasks/main.yml
mkdir handlers
touch handlers/main.yml
mkdir templates
touch templates/ntp.conf.j2
mkdir files
touch files/bar.txt
mkdir vars
touch vars/main.yml
mkdir defaults
touch defaults/main.yml
mkdir meta
touch meta/main.yml
mkdir library
mkdir module_utils
mkdir lookup_plugins
cd ..
cd webtier
mkdir tasks
touch tasks/main.yml
mkdir handlers
touch handlers/main.yml
mkdir templates
touch templates/ntp.conf.j2
mkdir files
touch files/bar.txt
mkdir vars
touch vars/main.yml
mkdir defaults
touch defaults/main.yml
mkdir meta
touch meta/main.yml
mkdir library
mkdir module_utils
mkdir lookup_plugins
cd ..
cd monitoring
mkdir tasks
touch tasks/main.yml
mkdir handlers
touch handlers/main.yml
mkdir templates
touch templates/ntp.conf.j2
mkdir files
touch files/bar.txt
mkdir vars
touch vars/main.yml
mkdir defaults
touch defaults/main.yml
mkdir meta
touch meta/main.yml
mkdir library
mkdir module_utils
mkdir lookup_plugins
